name: Terraform CI/CD

on:
  push:
    branches:
      - main  # Adjust to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0  # Specify the Terraform version you need
    
    - name: Terraform init
      run: terraform init
      
    - name: Terraform validate
      run: terraform validate

    - name: Terraform fmt
      run: terraform fmt -check=true -diff=true
      
    - name: Terraform plan
      run: terraform plan -out=tfplan
    
    - name: Run TFLint
      run: tflint -f compact
      
    - name: Terraform apply
      run: terraform apply -auto-approve tfplan